<?php

declare(strict_types=1);
/**
 * This file is part of qbhy/hyperf-auth.
 *
 * @link     https://github.com/qbhy/hyperf-auth
 * @document https://github.com/qbhy/hyperf-auth/blob/master/README.md
 * @contact  qbhy0715@qq.com
 * @license  https://github.com/qbhy/hyperf-auth/blob/master/LICENSE
 */
namespace Qbhy\HyperfAuth\Guard;

use Qbhy\HyperfAuth\Authenticatable;

class OnceGuard extends JwtGuard
{
    public function getClients(): array
    {
        return $this->config['clients'] ?? [];
    }

    public function user(?string $token = null): ?Authenticatable
    {
        return parent::user($token); // TODO: Change the autogenerated stub
    }

    public function login(Authenticatable $user)
    {
        return parent::login($user); // TODO: Change the autogenerated stub
    }

    public function logout($token = null)
    {
        return parent::logout($token); // TODO: Change the autogenerated stub
    }
}
